
- name: Infra - Install packages - Ubuntu
  include_tasks: debian10/commons.yaml
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int >= 18

- name: Infra - Install packages - Debian
  include_tasks: debian10/commons.yaml
  when: ansible_distribution == "Debian" and ansible_distribution_major_version|int >= 10

- name: Infra - Install packages - System not supported
  fail: msg="This System is not supported"
  when: |
    (ansible_distribution == "Ubuntu" and ansible_distribution_major_version|int < 18) or
    (ansible_distribution == "Debian" and ansible_distribution_major_version|int < 10) or
    (ansible_distribution != "Ubuntu" and ansible_distribution != "Debian")