= Terraform

The terraform module can work independently of running Ansible, but it is recommended to run it through Ansible, in order to enable the full flow.

The resources generated are the following:

* DynamoDB table
* S3 bucket
* IAM user
* Policies for the IAM user to all resources, including the EKS
* SNS Topic and Subscription

To run it in isolation, it is necessary to enter the terraform directory, and configure the variables in the variables.tfvars file.

A condition that the execution requires is to have a keybase user to encrypt with a pgp key the credentials of the IAM user generated by the terraform module.

It can be installed on ubuntu in the following way:

[source,bash]
----
sudo apt-get update && sudo apt-get install -y gnupg software-properties-common curl
curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
sudo apt-get update && sudo apt-get install terraform
----

The module can be run with my keybase identity, but then I won't be able to follow the flow with ansible, since there will be no way to decrypt the aws credentials. Therefore, it is necessary to create a new entity in keybase link:https://keybase.io/[Keybase], and use it within the terraform module, at the same time as configuring the console session to be authenticated against keybase and be able to execute the command (after running the terraform infrastructure build):

[source,bash]
----
terraform output -json passwords | jq -r '.["userName"]' | base64 --decode | keybase pgp decrypt
----

You can choose to disable the creation of sns, dynamodb and s3 resources.

WARNING: OJO

**It is assumed that the AWS credentials are correctly configured for the user running terraform, and that the profile has been chosen in the providers.tf**

To run the module just go to the terraform folder and run:

[source,bash]
----
terraform apply -var-file variables.tfvars
----

The ouputs have been configured so that they return the information that the rest of the ansible roles need to execute everything correctly.