apiVersion: v1
kind: Pod
metadata:
  name: node-port-scrapper
spec:
  containers:
  - command: ["/bin/sh"]
    args: ["-c", "nsenter --target '1' --mount --uts --ipc --net --pid < scrap-ports.sh"]
    image: rschamizo/node-port-scrapper
    imagePullPolicy: Always
    name: scrapper
    resources: {}
    env:
      - name: WHITE_LIST_PORT_STRING
        value: "10249 5353 17500"
    securityContext:
      privileged: true
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostNetwork: true
  hostPID: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30